Status em 2021-01-14 12:20
Motivo Depósito
===============

DESENVOLVIMENTO
---------------
1) Edição de filtro acrescenta e remove critérios visualmente
2) Valida os critérios do filtro para a consulta
3) Faz consulta no banco de dados (pendente: não usa os critérios)
4) Lista os dados retornados da consulta (pendente: paginação e ordenamento de colunas)
5) Exibe registro selecionado
6) Apresenta formulário para inclusão e alteração (erro: falha na integração com o FACADE)

PENDENTE
--------
1) Desenvolver classe utilitária para traduzir os critérios do filtro e repassar para o FACADE, no momento da consulta
2) Implementar paginação
3) Implementar ordenamento por coluna
4) Ajustar Look & Feel com logotipo do sistema
5) Acrescentar barra de progresso enquanto está realizando consulta (L&F)

FALHAS
------

1) INSERT
 * Falta o código do responsável (como obtê-lo?)

2021-01-14 12:12:27,231 [WebContainer : 5] DEPI-DepositoIdentificado ERROR br.com.bradseg.depi.depositoidentificado.funcao.action.cadastro.MotivoDepositoEditarAction$$EnhancerByCGLIB$$3fc9ef69 - Ocorreu um erro interno.
br.com.bradseg.depi.depositoidentificado.exception.DEPIIntegrationException: Ocorreu um erro interno.
 at br.com.bradseg.depi.depositoidentificado.funcao.action.cadastro.MotivoDepositoEditarAction.persistirDados(MotivoDepositoEditarAction.java:121) ~[classes/:na]
 at br.com.bradseg.depi.depositoidentificado.funcao.action.cadastro.MotivoDepositoEditarAction.enviar(MotivoDepositoEditarAction.java:92) ~[classes/:na]
 at br.com.bradseg.depi.depositoidentificado.funcao.action.cadastro.MotivoDepositoEditarAction$$FastClassByCGLIB$$17e18fb0.invoke(<generated>) ~[cglib-2.2.jar:na]
...
Caused by: br.com.bradseg.bsad.framework.core.exception.IntegrationException: msg.erro.campo.obrigatorio - C?digo do Respons?vel

2) UPDATE
  * Deve estar validando se o registro já existe na base (de fato é um UPDATE)

2021-01-14 12:14:51,360 [WebContainer : 7] DEPI-DepositoIdentificado ERROR br.com.bradseg.depi.depositoidentificado.funcao.action.cadastro.MotivoDepositoEditarAction$$EnhancerByCGLIB$$3fc9ef69 - Ocorreu um erro interno.
br.com.bradseg.depi.depositoidentificado.exception.DEPIIntegrationException: Ocorreu um erro interno.
 at br.com.bradseg.depi.depositoidentificado.funcao.action.cadastro.MotivoDepositoEditarAction.persistirDados(MotivoDepositoEditarAction.java:121) ~[classes/:na]
 at br.com.bradseg.depi.depositoidentificado.funcao.action.cadastro.MotivoDepositoEditarAction.enviar(MotivoDepositoEditarAction.java:92) ~[classes/:na]
 at br.com.bradseg.depi.depositoidentificado.funcao.action.cadastro.MotivoDepositoEditarAction$$FastClassByCGLIB$$17e18fb0.invoke(<generated>) ~[cglib-2.2.jar:na]
...
Caused by: br.com.bradseg.bsad.framework.core.exception.BusinessException: msg.erro.customizada : Motivo Dep?sito com Descri??o B?sica: TESTEE j? est? cadastrado.
 at br.com.bradseg.depi.depositoidentificado.dao.MotivoDepositoDAOImpl.alterar(MotivoDepositoDAOImpl.java:127) ~[classes/:na]
...

Departamento
============

DESENVOLVIMENTO
---------------
1) Edição de filtro acrescenta e remove critérios visualmente
2) Valida os critérios do filtro para a consulta
3) Faz consulta no banco de dados (pendente: não usa os critérios)
4) Lista os dados retornados da consulta (pendente: paginação e ordenamento de colunas)
5) Apresenta formulário para inclusão e alteração (erro: falha na integração com o FACADE)

PENDENTE
--------
1) Desenvolver classe utilitária para traduzir os critérios do filtro e repassar para o FACADE, no momento da consulta
2) Implementar paginação
3) Implementar ordenamento por coluna
4) Ajustar Look & Feel com logotipo do sistema
5) Acrescentar barra de progresso enquanto está realizando consulta (L&F)

FALHAS
------
1) LISTA
  Acrescentar campo ultimaAtualizacao

2) EXIBIÇÃO DE 1 REGISTRO
2021-01-14 12:00:58,769 [WebContainer : 5] DEPI-DepositoIdentificado INFO  br.com.bradseg.depi.depositoidentificado.dao.DepartamentoDAOImpl - obterPorChave(DepartamentoVO vo)
2021-01-14 12:00:58,795 [WebContainer : 5] DEPI-DepositoIdentificado ERROR br.com.bradseg.depi.depositoidentificado.funcao.action.cadastro.DepartamentoEditarAction$$EnhancerByCGLIB$$f871b4ca - No value supplied for the SQL parameter 'prm1': No value registered for key 'prm1'
br.com.bradseg.bsad.framework.core.exception.IntegrationException: No value supplied for the SQL parameter 'prm1': No value registered for key 'prm1'
 at br.com.bradseg.bsad.framework.core.exception.support.ExceptionAspect.handle(ExceptionAspect.java:45) ~[BSAD-Foundation-Core-3.6.10.jar:3.6.10]
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0]
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90) ~[na:1.8.0]
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55) ~[na:1.8.0]
 at java.lang.reflect.Method.invoke(Method.java:508) ~[na:1.8.0]
 at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:621) ~[spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
 at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:610) ~[spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
 at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:65) ~[spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:161) ~[spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
 at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:80) ~[spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
 at br.com.bradseg.bsad.framework.core.logging.support.LoggingAspect.handle(LoggingAspect.java:68) ~[BSAD-Foundation-Core-3.6.10.jar:3.6.10]
 at sun.reflect.GeneratedMethodAccessor33.invoke(Unknown Source) ~[na:na]
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55) ~[na:1.8.0]
 at java.lang.reflect.Method.invoke(Method.java:508) ~[na:1.8.0]
 at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:621) ~[spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
 at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:610) ~[spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
 at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:65) ~[spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
 at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:90) ~[spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
 at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:621) ~[spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
 at br.com.bradseg.depi.depositoidentificado.facade.DepartamentoFacadeImpl$$EnhancerByCGLIB$$38cf5f04.obterPorChave(<generated>) ~[cglib-2.2.jar:na]
 at br.com.bradseg.depi.depositoidentificado.funcao.action.cadastro.DepartamentoEditarAction.obterPeloCodigo(DepartamentoEditarAction.java:145) ~[classes/:na]
 at br.com.bradseg.depi.depositoidentificado.funcao.action.cadastro.DepartamentoEditarAction.preencherFormulario(DepartamentoEditarAction.java:129) ~[classes/:na]
 at br.com.bradseg.depi.depositoidentificado.funcao.action.cadastro.DepartamentoEditarAction.detalhar(DepartamentoEditarAction.java:74) ~[classes/:na]
 at br.com.bradseg.depi.depositoidentificado.funcao.action.cadastro.DepartamentoEditarAction$$FastClassByCGLIB$$edc0473.invoke(<generated>) ~[cglib-2.2.jar:na]
 at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:191) ~[cglib-2.2.jar:na]
 at org.springframework.aop.framework.Cglib2AopProxy$CglibMethodInvocation.invokeJoinpoint(Cglib2AopProxy.java:688) ~[spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) ~[spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
 at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:80) ~[spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
 at br.com.bradseg.bsad.framework.core.logging.support.LoggingAspect.handle(LoggingAspect.java:68) ~[BSAD-Foundation-Core-3.6.10.jar:3.6.10]
 at sun.reflect.GeneratedMethodAccessor33.invoke(Unknown Source) ~[na:na]
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55) ~[na:1.8.0]
 at java.lang.reflect.Method.invoke(Method.java:508) ~[na:1.8.0]
 at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:621) ~[spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
 at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:610) ~[spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
 at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:65) ~[spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
 at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:90) ~[spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
 at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:621) ~[spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
....